### ISSUE TITLE
Block screen rotation in app

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/android-native-xsens#112]
## Description

The screen should not be able to rotate while we use the application since we only support portrait mode.

## Must Include

- [x] Block screen rotation

**Comment by tfiedlerdev** [comment]
This is a quick fix, not a long term solution. See this [Stackoverflow post](https://stackoverflow.com/questions/582185/how-can-i-disable-landscape-mode-in-android) for an explanation
