### ISSUE TITLE
Add option to save camera skeletons during recording

### ISSUE THREAD

**Issue by alexanderwischmann** [Sensors-in-Paradise/android-native-xsens#147]
## Description
It would be nice to optionally record a camera video when recording sensor data from a person. This Video could then be used to extract a persons Skeleton via tensorflow and store that information (not the video itself) in addition to the sensor data.

## Must Include

- [x] #148
- [x] Integration of the required Tensorflow model to create skeleton
- [x]  Show live skeleton 
- [x] clean code
- [x]  Saving the skeleton data alongside the sensor data to external storage

**Comment by lucasliebe** [comment]
is already done
