### ISSUE TITLE
Record Example Data

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/android-native-xsens#15]
## Description

Record Activities of great difference with 5 Sensors and the App.

## Must Include

- [ ] one activity with at least 50 recordings
- [ ] second activity with at least 50 recordings
- [ ] third activity with at least 50 recordings
- [ ] fourth activity with at least 50 recordings
- [ ] fifth activity with at least 50 recordings

## Notes
- follow Guidelines in Notion!
- each recording at least 10 seconds

**Comment by FranzSw** [comment]
I guess it would be good if we all work on this issue to get a diverse example Data set.

Also let's pick at least a few activities that are similar to each other to explore benefits of an LSTM

**Comment by lucasliebe** [comment]
for our current model that is correct but assuming we want to use the same model to also train the lstm with it that combines the windows it might be beneficial to make smaller recordings so that we dont have to split our recordings afterwards for this. But of course you could record longer, i just want 50 recordings of at least 10 seconds
Activities will be chosen and added on 29.11.

**Comment by lucasliebe** [comment]
**Paused** until we get new straps since data might change with these. ML Team should still collect some data to develop their model.

**Comment by lucasliebe** [comment]
can be closed since data needed will be changed soon
