### ISSUE TITLE
Independence from XSens App: Rework Synchronization

### ISSUE THREAD

**Issue by kpostnov** [Sensors-in-Paradise/android-native-xsens#152]
## Description

Assuming the app will be used by the chair after our project ends, it would be useful to not have a need for two apps - our app and the official XSens app. Currently we use the XSens app to synchronize the sensors as our app fails to achieve that oftentimes. Therefore a rework is needed.

## Must Include

- [x] rework synchronization so that it works like in the XSens app
- [x] optional: Show progress percentage (see XSens app)

**Comment by lucasliebe** [comment]
Synchronizations seems to work fine by now. I will close this issue until we have more problems. Percentage is also shown already
