### ISSUE TITLE
Improve labeling screen

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/android-native-xsens#35]
## Description

Some features need improvement on this screen.

## Must Include

- [x] prevent logger from closing too early! (quickfix done)
- [x] only record with sensors connected
- [x] discard recording

**Comment by kpostnov** [comment]
Assuming #45 will be implemented, discarding recordings will become obsolete.

**Comment by kpostnov** [comment]
Closed by #63.
