### ISSUE TITLE
Local Linter

### ISSUE THREAD

**Issue by tfiedlerdev** [Sensors-in-Paradise/android-native-xsens#4]
## Description

Implement an automated linter e.g. Prettier / ESLint... in order to keep code clean, add linter configuration to project locally

## Must include

- [x] Explanation to others

**Comment by lucasliebe** [comment]
my choice for linting kotlin goes to detekt, for reference visit [Detekt Website](https://detekt.github.io/detekt/)

**Comment by lucasliebe** [comment]
everyone that didnt get an introduction yet please come to me if you want one
