### ISSUE TITLE
Add `sensor-body position` relation  UI 

### ISSUE THREAD

**Issue by tfiedlerdev** [Sensors-in-Paradise/android-native-xsens#41]
## Description
Currently we have hardcoded the relation of sensor (MAC-address) to body position (or index in sensor data). Later, with more sensors it would be nice if one could assign a sensor to a body position via UI in the app, which then determines the order of the captured sensor data

## Must Include

- [ ] UI assign (connected) sensors to body positions

## Notes
![image](https://user-images.githubusercontent.com/29177177/143030719-ecc60ba9-082c-4664-b502-a198cf9fe102.png)

**Comment by lucasliebe** [comment]
first issue towards this idea is #62
