### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by tfiedlerdev** [Sensors-in-Paradise/android-native-xsens#5]
## Description

Add android testing & Linting CI in github repo

## Must include

- [x] CI in this repo + quickguide for future ones

**Comment by lucasliebe** [comment]
added basic CI for building the project, if this works we can do more

**Comment by lucasliebe** [comment]
CI working for Linter and Building, more can be done in the future

Or should this remain open until also other tests are implemented and running in CI?
