### ISSUE TITLE
label multipart recordings

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/android-native-xsens#52]
## Description

For our goal to identify activities in a larger recording, we need to be abled to label parts of recordings and save this information next to recordings.

## Must Include

- [x] A way of storing activity labels next to recordings with timestamps of start and end
- [x] save files in folders only considering person and not the label

## Notes

optional:
- [x] add unremovable null activity to choosable activities

**Comment by tfiedlerdev** [comment]
- [ ] TODO: remove bugs
