### ISSUE TITLE
data export after recording

### ISSUE THREAD

**Issue by treyfel** [Sensors-in-Paradise/android-native-xsens#57]
### Must Include

- [x]  button export all data
- [x] ensure connection when clicking
- [ ] implement proper structure for exported data quantities
- [x] delete all exported recordings afterwards

### Notes

for exporting free acceleration, some math has done be done first since the current firmware doesnt support this. Check the section on recording data in the user manual (e.g. selecting few devices at once for exporting via bluetooth, since otherwise data might be lost)

....
What does the second Task mean? Do we immediately want to export data onto the connected phone? I think this would destroy the purpose of saving on the devices, since we would have to make sure, that the devices are properly connected when stopping the recording. IMO: we should make exporting the data a separate functionality... sth  like a button: exportAll,  that exports all the recorded data to a connected devices, ensuring proper connection and deleting the exported data on all sensors afterwards.

_Originally posted by @treyfel in https://github.com/Sensors-in-Paradise/android-native-xsens/issues/36#issuecomment-981789436_

**Comment by lucasliebe** [comment]
we discussed today that we want to have the export after we finished the recording. if files are transferred completely the app will signalize to the sensors so they can delete the recording. starting a new recording while exporting needs to be possible for this!

**Comment by lucasliebe** [comment]
this functionality is deprecated and will not be implemented in our scope
