### ISSUE TITLE
Connection Timeout/Cancel

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/android-native-xsens#58]
## Description

Sometimes Sensors don't connect which leads to the need to restart the application.

## Must Include

- [x] Cancel Connection Button and/or Add a timeout after 3 seconds for connecting sensors
- [x] reload available sensors by button on top right since sensors remain visible even if not available anymore

**Comment by alexanderwischmann** [comment]
No timeout implemented as cancel connection button should be sufficiant

**Comment by alexanderwischmann** [comment]
Cancel button is disabled while syncing any sensors, because it wouldn't work in that case  (even on non-syncing sensors).
