### ISSUE TITLE
Request permissions in app 

### ISSUE THREAD

**Issue by tfiedlerdev** [Sensors-in-Paradise/android-native-xsens#66]
## Description
As a user of the app I don't want to grant the required permissions in the system settings on each new install of the app but inside our app.  

## Must Include

- [x] Request ALL required permissions from inside the app [Look here](https://developer.android.com/training/permissions/requesting)

**Comment by alexanderwischmann** [comment]
Request is launched JUST on activity creation. After denying the permissions 2 times, you have to enable them manually in the settings to use the app.
