### ISSUE TITLE
Guidelines on Notion

### ISSUE THREAD

**Issue by tfiedlerdev** [Sensors-in-Paradise/android-native-xsens#8]
## Description

create wiki

## Must include

- [x] tickets
- [ ] Code
- [x] use of sensors
- [x] #4

**Comment by lucasliebe** [comment]
Changed to Notion because its more central than per repository and better than Readme.md in Organisation

**Up for discussion**

**Comment by lucasliebe** [comment]
Coding Guidlines will be discussed on Thursday 11.11.21
