### ISSUE TITLE
Add visualization of activity count

### ISSUE THREAD

**Issue by tfiedlerdev** [Sensors-in-Paradise/android-native-xsens#84]
## Description
As a data recorder we want to see a summary of recorded activities (ie which activity was recorded how many times). 
We want there to be a button "Show summary of recordings" or similar which opens a dialog showing the summary (would be best if it was a pie chart (as a popup?))

## Must Include

- [x] Button on Recording page "Show summary of recordings"
- [x] Dialog showing Pie chart or similar when Button is clicked

## Notes

Currently it is displayed as follows: 
![image](https://user-images.githubusercontent.com/29177177/148753850-cc4ac676-e550-4c6b-971b-ddad28a92d67.png)

**Comment by treyfel** [comment]
Maybe this can be a starting point for adding different kinds of visualiyations. E.g. pie chart for this issue and then bar chart, some clustering or similar in the future.

**Comment by tfiedlerdev** [comment]
This is being done within #163 . The visualization will then be part of the on device training screen
