### ISSUE TITLE
Save preprocessed Data

### ISSUE THREAD

**Issue by lucasliebe** [Sensors-in-Paradise/android-native-xsens#87]
## Description

We want to save preprocessed Data of the prediction screen together with the original recording, if the preference for it is set.

## Must Include

- [ ] save file for preprocessed data
- [ ] make the implementation generic (no hard coded names etc)
- [ ] save files for recorded data before preprocessing

**Comment by kpostnov** [comment]
I have implemented this issue in `87-save-preprocessed-data-2`. The branch is not intended to be merged as logging is not using the LoggingManager so far. Furthermore, this functionality probably will be used only once to check the app preprocessing.

**Comment by lucasliebe** [comment]
Will be reopened with settings for it
